apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-frontend
resources:
  - ../../../base/frontend/admin
images:
  - name: ghcr.io/knighthacks/admin-tool-frontend-2022
    newName: ghcr.io/knighthacks/admin-tool-frontend-2022 # {"$imagepolicy": "flux-system:admin-frontend:name"}
    newTag: 1.0.0 # {"$imagepolicy": "flux-system:admin-frontend:tag"}
