apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-router-ingress
spec:
  podSelector:
    matchLabels:
      'app.kubernetes.io/part-of': knighthacks-microservices
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              'kubernetes.io/metadata.name': knighthacks-router
  egress:
    - {}