apiVersion: v1
data:
    DATABASE_URI: ENC[AES256_GCM,data:4PkfrORWYQQXRJpiMT5XPMx1C9iHlClE1ok1iacfOBVo2Zf+1hspYEml9yZ2wqvr3A==,iv:auNy4wIhTp2rjhPtWy4O79L2XhaNKKRy2IHaYvsQrGE=,tag:NVOYhqTiSVsr9iq1bT2ksg==,type:str]
kind: Secret
metadata:
    name: database
    namespace: knighthacks-microservices
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-15T04:04:14Z"
    mac: ENC[AES256_GCM,data:+LbWu4KJj5IQ45Fy0PVf3D+hZkrDL4MOXaLAAPVC3s3Ie506suR56yylIIph82suQn9wxNRGdW8PJn6sqauOUxfKH9mm9PslQBedUUj8Se0LJdwLVD1Cy/bgWt547ZaO2Uj+bMHECek2rgFB5KA++va0CdHxTouFUIrZNSLqmio=,iv:bCO5gf5QlPAtPAj/2ZIzxs2QjSHOVzNVahIQH+nLmsE=,tag:Ho22W1Pw8qBQwGBICoiynw==,type:str]
    pgp:
        - created_at: "2023-06-15T04:04:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8sQ91dP//QxARAArYdX5UbwXFlST+/aYRvoTRt0dS7i8+aO5VZp9WD8Yzq3
            Men+pHlsEEGeHvDEyJM95DF3tGp1fR24HZXXR0eqVsfSmhslKXS7o3wqgXE6NWwA
            bNAKBz0BPHGuGW7FY3ENOP/Jo0SEjaR36WT2mhAJzlBXeTc/KcABm+IFpVYwKTX/
            Hb6PLmukiy1QeVxs/j6haGWW50vRzzv3kIMxNvpT+Bd8ibKcx7E5G5+HyPev2+NE
            I6WYCnnjSXJb3UVzqrM/cIH41qnWbqfdri5ZTWs042re8ScuvPmzwm8FaO2zknZA
            Ln1O7M9/vkVoGwXIdkvY2mTyYNCDDn5nXt71Fcro91VFrwN/pKdEHJqgwurq8INm
            /IBshllh15cFBHBzn0ytTCb0wU3ARXFO0C+I2p5MNBfzaWwvvje35AIkmPzrSp54
            HcRsPgXL5DSSBbYsCiXMB6HlMvKnQ0usL6Nx+5Ufo2fQkloFpGqR2DntSUDbAX3d
            jxGnDm3BVewWhHtg/LxKT9a3+0WCqelkdTaSgmAN46lX2q7JDJA4qRIj086yvwYa
            fKQcPcR08TDvWMfEoQ5dknwDSxk/kj038Jbvc6OE0DK0fTgyMuhy5dNPpgZI289V
            T/iFT7GR0peimu2pv6/AP8yTz3t8x1ty5NteKZnBpW4YgoLDm76ph9wIbVjeB6HS
            XgGYCHdw8Q+ZIIADne2Y+oAl8sMt09y9uyHkCRLi/CRxecInqoT0KSVQyXPUyWJF
            j+riQRMKpHrXRqXK5fzUBHKTVCTd+agBYUVYCk5fk0OW1M5ye7oc5Lsqr3pID0I=
            =05RU
            -----END PGP MESSAGE-----
          fp: AB85EAEF0CE58CAB13647A5941285A90A632C0E2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
