apiVersion: v1
kind: Secret
metadata:
    name: login-encryption
    namespace: knighthacks-microservices
data:
    AES_CIPHER: ENC[AES256_GCM,data:PrzKaKkfKlK1fnxa/xjrSvcnQkjRHfJmgC6kW5dakA/kuKW/HySy/vkyuR8=,iv:skpCDoujuhYF2S4k7czdk6RL43lEuGJUR7e2f4/hwmU=,tag:Go0zWXIpkfury/tddeixLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-14T05:07:54Z"
    mac: ENC[AES256_GCM,data:IK+sImW1kOIM3zr/xUOAsLdpjP6rICIacn4ll4noLhRxyXfppWu4/Ypo/g4q9QJrC9dSAjIwSRmQmIEmYfyBcGa2ow0T0e770hwT45risPNVRppe2J3hJd7HhfZSPwSLJl+MhWN0irDgLG96pfanUcex9/ROi9MMjJDk24fh4I8=,iv:Lbjtz1+szDglgkVSEuDaXD7QLtSb80poJW2x+gvAXy0=,tag:PlLPMQr6NoqA4QD6Q+8NOw==,type:str]
    pgp:
        - created_at: "2022-06-14T05:07:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+1NVVTpL0x2ARAAt4f71wNbKVBDa0vGYlFKdAAm+0xK4Nkf5a2QhmfC6fda
            LtVyqBTAGOojpx/gQGvls73Em3ZDFt7xMGMg5aG0lROs7xigY9JFSKBjoP1oeUim
            jnwV+CX/6zzIWyco52OMGHrVN6KVfBEj8i6Org7AHdunxksNDVP+W29u5nTU/+Bk
            62RhQcqyOastw2uvG2H5Tf11aHppAy/ILIqbu0W2NlcIRpVlZSRyG1a9VbPz4OB4
            P1h1FPfh0Ln2zNWdrkZSFh8MX31Fu+sFRFs+RIqMpe/BUpVQWRDrISkQ8mjbHUCE
            OQ/gAmCjE+/av7gxeN4RR0CsslvyeUrwJrY4kACUE3AYFgs7m7QooAvRahBk8jTL
            xMIOobs2LNFxUxbJ9NtFmQF9TPdg8Z+iQz7BSnUijiURNuTMl10/UnOQXgM6bN25
            Sr2r9a8gRG+W8UeN+ymU0TvbuoHHiq/zICBA3gZEuG/TpA0tW4Cc0RYEgYeUaI7A
            f6kaSnsNU0y/mfmlgErZgsNsMjJl8IROAogJXRudVocUPkRs0qRuuhub0IzgRpJ9
            WNmsMrR93N/wqqeEY4iyU5WDKLHjNWsyesDcNQk6BDHHG+TvAjPTOKQ4srKzW/7L
            lY7iBu426mPAcRnk1MdZ4eQMBIg98AkHxpdDhDxT9ngYkwrUf2ocGpe4XYzqwgvS
            XgGlnywcVAjkgmGc3MTGgVTV+96pLyVGvt8WfYdQaArLmZ71DTVYNbq8Zxnq129L
            i97pWtC39Gcq5FPRow8eS5XonyjzEFqARoF3s+l62/NZskvgBh73z4HaXEXzjjg=
            =LX26
            -----END PGP MESSAGE-----
          fp: 52A7AB3824CA4A6C8012189A88014D23C1883032
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
