kind: Secret
apiVersion: v1
metadata:
    name: oauth
    namespace: knighthacks-microservices
data:
    OAUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:wHJnNBHAuu3zc/tePLK4bsAuAdpDzXTW7BHS7A==,iv:vtUvUwCKVkZC61rzDjbQz/0lulChY+Gh9t8jO7y6UnQ=,tag:ywuFV82wpL21v8MUZ6Z07A==,type:str]
    OAUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:lP8o+lI/oQumQ7Wq25a1TBeUVUSJWZj3toh6vJtnECutyHVSfHrayq5cXurDneoY20m+l2ZZjvM=,iv:0RVWSBbf7w4g/GpocsOxZtoKC249fxBeITfoZC6W0o8=,tag:YYf6Rq2a2wg3vgQIsaNwbw==,type:str]
    OAUTH_GITHUB_REDIRECT_URL: ENC[AES256_GCM,data:sJrhJKpGO2ZW0amrKwV7xiM9u7HT3pODGZlGxuvOmXUS5UwhBRSOjKXvWV34w/La,iv:ZdDXSmjPfi5li5esJT6PNJvIBUVzo1YeH2sFWZYucYs=,tag:gUYHFXXm+0NH2+2IIKaODA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-14T05:03:47Z"
    mac: ENC[AES256_GCM,data:PpR5YfnIUdISUca/nRQNXLDAnpTxCsSOV9g8CuOWmhiEqa8W1+58+YCRoDd5tquVSgrwS8epO4ghrPBFzZwOOJPhja/9f7H+sxTh88cj1s94uFDkK3WWk5wLuFTOrQg1XOJI/Ajkm/duY9WdRmBMRt3XUZCRVBUw5iwCN96Ns2U=,iv:6g8d1yxEQZmhGc8idTOEC4U2YNPBoiHyL7WeeLKnEgU=,tag:M0sH24E5aIMDPbdtoJe41Q==,type:str]
    pgp:
        - created_at: "2022-06-14T05:03:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+1NVVTpL0x2AQ//V38pkGS+2gWBkDSXHJ+aSnDEs1oXe1dgxWVPpy9o5ZN9
            zfAIQADsNykX82QzM8omnN7Kqj8ygA+8Uw30fDRdd73rl9VXA5woKSgxEv+WZuRX
            G9DxBlzV9Fn7AWQND0gC8TmDcKLUiREBD6wkIXlA7PeYaxc0n6/M8s4DAk6Re82T
            DblOzAlIvE9IZ5sJrHT5kH1pxa1a9IUBuPVdP1XsaDEVXJDoaQsM4mb2lQ2r/O+z
            yIaU5NyA4qyO1ButT5jDqwxnIdrT5407RTVFIHN7PcUVdrTPliPBIdQ+V7XpZ8o1
            Hd1UJKrmbzQqi0ygwVHyUqtZaNm3xqIkuJZ6cQfA4YWX++49Cg3oI/QIc4Ppd8c3
            JDptadNnwbFoPPcEyNhXSKZm8yKiTZFbeUoVubt57ljI7LHgkATv3JupMC1T22/e
            I0z4AO6ee8QG7Slwf4+HcoQvvrfdYk8tTYz4sZoVHl6jooSMBcSX9b3+eRQh4vOo
            hrHdOOtBdIJ775Zb+5J/75+o031MV4Nt/njvVY/4PaZfW/Hb8LI5TbvvUOwGJezq
            sNb7Ayx25Tgq+uXO2SfIlfOYxxsZAOD9pwctx1q6qUrk3smAdDujk/fk2paFDaTz
            R+qCwTegiQMe3d4+3g+Tr85oeCA7+tZ1NKcyX9weWSWnj7l/2h7EYie6xJoko7zS
            XgGU08PDNupeuj3MFO167hcX4T5jrLSNhA84QESR2KhyDY8+qo5GV0TAUsszoYzR
            Hm1EBjKC6oLHbTKeGV/GLF0ouTHksYcRsTit5pHdim4q/ScWlnW7iNRE6AbtMyA=
            =tpPD
            -----END PGP MESSAGE-----
          fp: 52A7AB3824CA4A6C8012189A88014D23C1883032
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
