apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apollorouter
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/KnightHacks/router
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/chart