apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-router
resources:
  - ./dev-ssl.yaml
  - ./release.yaml
configMapGenerator:
  - name: apollorouter-config
    files:
      - values.yaml=values.yaml
  - name: apollosupergraph-config
    files:
      - supergraph.graphqls=supergraph.graphqls
  - name: rhai-script-config
    files:
      - script.rhai=script.rhai
configurations:
  - kustomizationconfig.yaml