apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-router
resources:
  - ./release.yaml
configMapGenerator:
  - name: apollorouter-config
    files:
      - values.yaml=values.yaml
  - name: apollosupergraph-config
    files:
      - supergraph.graphqls=supergraph.graphqls
configurations:
  - kustomizationconfig.yaml