apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hackathon-ingress
spec:
  podSelector:
    matchLabels:
      'app.kubernetes.io/name': hackathon
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}