apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  namespace: knighthacks-frontend
  labels:
    app.kubernetes.io/name: hackathon
    app.kubernetes.io/part-of: knighthacks-frontend
    app.kubernetes.io/version: "main-a81e9e5f-1672425959" #  {"$imagepolicy": "flux-system:hackathon-frontend:tag"}
    app: hackathon-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hackathon
      app.kubernetes.io/part-of: knighthacks-frontend
      app: hackathon-2022
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hackathon
        app.kubernetes.io/part-of: knighthacks-frontend
        app: hackathon-2022
    spec:
      containers:
        - name: hackathon
          image: ghcr.io/knighthacks/hackathon-2022:main-a81e9e5f-1672425959 # {"$imagepolicy": "flux-system:hackathon-frontend"}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env: # TODO: MOVE THIS INTO A VARIABLE
            - name: REACT_APP_API_ENDPOINT
              value: 'https://api-dev.knighthacks.org/'
            - name: REACT_APP_OAUTH_AUTH_REDIRECT
              value: 'https://2023.knighthacks.org/auth_redirect'