apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  labels:
    app.kubernetes.io/version: "main-a81e9e5f-1672425959" #  {"$imagepolicy": "flux-system:hackathon-frontend:tag"}
spec:
  template:
    spec:
      containers:
        - name: hackathon
          image: ghcr.io/knighthacks/hackathon-2022:main-a81e9e5f-1672425959 # {"$imagepolicy": "flux-system:hackathon-frontend"}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-hackathon-config