apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knighthacks-hackathon-frontend
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 400, 401"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "origin"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
    - host: dev.knighthacks.org
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: knighthacks-hackathon-frontend
                port:
                  number: 80
    - host: 2023.knighthacks.org
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: knighthacks-hackathon-frontend
                port:
                  number: 80