apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-frontend
commonLabels:
  app.kubernetes.io/name: hackathon
  app.kubernetes.io/part-of: knighthacks-frontend
  app: hackathon-2022
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - allow-hackathon-ingress.yaml