nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
      - path: spec/values/primary/initdb/scriptsConfigMap
        kind: HelmRelease