---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '>11.0.0'
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
  values:
    primary:
      initdb:
        scriptsConfigMap: initdb-scripts
