apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app.kubernetes.io/version: "main-310098cc-1672714491" #  {"$imagepolicy": "flux-system:admin-frontend:tag"}
spec:
  template:
    spec:
      containers:
        - name: admin
          image: ghcr.io/knighthacks/admin-tool-frontend-2022:main-310098cc-1672714491 # {"$imagepolicy": "flux-system:admin-frontend"}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-admin-config