apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  namespace: knighthacks-frontend
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: knighthacks-frontend
    app.kubernetes.io/version: "1.0.0" #  {"$imagepolicy": "flux-system:hackathon-frontend:tag"}
    app: knighthacks_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin
      app.kubernetes.io/part-of: knighthacks-frontend
      app: knighthacks_frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin
        app.kubernetes.io/part-of: knighthacks-frontend
        app: knighthacks_frontend
    spec:
      containers:
        - name: admin
          image: ghcr.io/knighthacks/admin-tool-frontend-2022:1.0.0 # {"$imagepolicy": "flux-system:hackathon-frontend"}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: REACT_APP_API_ENDPOINT
              value: 'https://api-dev.knighthacks.org/'
            - name: REACT_APP_OAUTH_AUTH_REDIRECT
              value: 'https://2023.knighthacks.org/auth_redirect'