apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-frontend
commonLabels:
  app.kubernetes.io/name: admin
  app.kubernetes.io/part-of: knighthacks-frontend
  app: admin-tool-frontend-2022
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - allow-admin-ingress.yaml