apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-microservices
resources:
  - ../../../base/microservices/knighthacks_events
images:
  - name: ghcr.io/knighthacks/knighthacks_events
    newName: ghcr.io/knighthacks/knighthacks_events # {"$imagepolicy": "flux-system:knighthacks-events:name"}
    newTag: main-eabeb9e3-1660266760 # {"$imagepolicy": "flux-system:knighthacks-events:tag"}
