apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-users
  labels:
    app.kubernetes.io/version: "main-cb1394db-1672790504" # {"$imagepolicy": "flux-system:knighthacks-users:tag"}
spec:
  template:
    spec:
      containers:
        - name: knighthacks-users
          image: ghcr.io/knighthacks/knighthacks_users:main-cb1394db-1672790504 # {"$imagepolicy": "flux-system:knighthacks-users"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
