apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-users
  namespace: knighthacks-microservices
  labels:
    app.kubernetes.io/name: knighthacks-users
    app.kubernetes.io/part-of: knighthacks-microservices
    app.kubernetes.io/version: "main-1baa6512-1665098966" # {"$imagepolicy": "flux-system:knighthacks-users:tag"}
    app: knighthacks_users
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knighthacks-users
      app.kubernetes.io/part-of: knighthacks-microservices
      app: knighthacks_users
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knighthacks-users
        app.kubernetes.io/part-of: knighthacks-microservices
        app: knighthacks_users
    spec:
      containers:
        - name: knighthacks-users
          image: ghcr.io/knighthacks/knighthacks_users:main-1baa6512-1665098966 # {"$imagepolicy": "flux-system:knighthacks-users"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
