apiVersion: v1
kind: Service
metadata:
  name: 'knighthacks-users-api'
  labels:
    app.kubernetes.io/name: knighthacks-users
    app.kubernetes.io/part-of: knighthacks-microservices
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: knighthacks-users
    app.kubernetes.io/part-of: knighthacks-microservices
