apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: 'development-'
resources:
  - ../../base/router
configMapGenerator:
  - name: apollosupergraph-config
    behavior: merge
    files:
      - supergraph.yaml=supergraph.yaml