apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces
  - ./router
  - ./microservices/knighthacks_users
  - ./microservices/knighthacks_events
  - ./microservices/knighthacks_sponsors
  - ./microservices/knighthacks_hackathon
  - ./microservices/secrets/
  - ./registries