apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knighthacks-microservices
resources:
  - ../../../base/microservices/knighthacks_hackathon
images:
  - name: ghcr.io/knighthacks/knighthacks_hackathon
    newName: ghcr.io/knighthacks/knighthacks_hackathon # {"$imagepolicy": "flux-system:knighthacks-hackathon:name"}
    newTag: main-39a08219-1671322315 # {"$imagepolicy": "flux-system:knighthacks-hackathon:tag"}
