apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-hackathon
  labels:
    app.kubernetes.io/version: "main-39a08219-1671322315" #  {"$imagepolicy": "flux-system:knighthacks-hackathon:tag"}
spec:
  template:
    spec:
      containers:
        - name: knighthacks-hackathon
          image: ghcr.io/knighthacks/knighthacks_hackathon:main-39a08219-1671322315 # {"$imagepolicy": "flux-system:knighthacks-hackathon"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
