apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-hackathon
  namespace: knighthacks-microservices
  labels:
    app.kubernetes.io/name: knighthacks-hackathon
    app.kubernetes.io/part-of: knighthacks-microservices
    app.kubernetes.io/version: ""#  {"$imagepolicy": "flux-system:knighthacks-hackathon:tag"}
    app: knighthacks_hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knighthacks-hackathon
      app.kubernetes.io/part-of: knighthacks-microservices
      app: knighthacks_hackathon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knighthacks-hackathon
        app.kubernetes.io/part-of: knighthacks-microservices
        app: knighthacks_hackathon
    spec:
      containers:
        - name: knighthacks-hackathon
          image: ghcr.io/knighthacks/knighthacks_hackathon:0.0.3 # {"$imagepolicy": "flux-system:knighthacks-hackathon"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption