apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/microservices/knighthacks_users
images:
  - name: ghcr.io/knighthacks/knighthacks_users
    newName: ghcr.io/knighthacks/knighthacks_users # {"$imagepolicy": "flux-system:podinfo:name"}
    newTag: 0.0.3 # {"$imagepolicy": "flux-system:podinfo:tag"}