apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-events
  labels:
    app.kubernetes.io/version: "main-a1de05f9-1671322319" #  {"$imagepolicy": "flux-system:knighthacks-events:tag"}
spec:
  template:
    spec:
      containers:
        - name: knighthacks-events
          image: ghcr.io/knighthacks/knighthacks_events:main-a1de05f9-1671322319 # {"$imagepolicy": "flux-system:knighthacks-events"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
