apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-sponsors
  namespace: knighthacks-microservices
  labels:
    app.kubernetes.io/name: knighthacks-sponsors
    app.kubernetes.io/part-of: knighthacks-microservices
    app.kubernetes.io/version: "main-712bb98b-1667012579" #  {"$imagepolicy": "flux-system:knighthacks-sponsors:tag"}
    app: knighthacks_sponsors
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knighthacks-sponsors
      app.kubernetes.io/part-of: knighthacks-microservices
      app: knighthacks_sponsors
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knighthacks-sponsors
        app.kubernetes.io/part-of: knighthacks-microservices
        app: knighthacks_sponsors
    spec:
      containers:
        - name: knighthacks-sponsors
          image: ghcr.io/knighthacks/knighthacks_sponsors:main-712bb98b-1667012579 # {"$imagepolicy": "flux-system:knighthacks-sponsors"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
