apiVersion: apps/v1
kind: Deployment
metadata:
  name: knighthacks-sponsors
  namespace: knighthacks-microservices
  labels:
    app.kubernetes.io/version: "main-5727f428-1671322333" #  {"$imagepolicy": "flux-system:knighthacks-sponsors:tag"}
spec:
  template:
    spec:
      containers:
        - name: knighthacks-sponsors
          image: ghcr.io/knighthacks/knighthacks_sponsors:main-5727f428-1671322333 # {"$imagepolicy": "flux-system:knighthacks-sponsors"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: oauth
            - secretRef:
                name: jwt
            - secretRef:
                name: login-encryption
