apiVersion: v1
kind: Service
metadata:
  name: 'knighthacks-sponsors-api'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: knighthacks-sponsors
    app.kubernetes.io/part-of: knighthacks-microservices
